# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"b\n\x11LocationEPMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t2E\n\x11LocationEPService\x12\x30\n\x06\x43reate\x12\x12.LocationEPMessage\x1a\x12.LocationEPMessageb\x06proto3')



_LOCATIONEPMESSAGE = DESCRIPTOR.message_types_by_name['LocationEPMessage']
LocationEPMessage = _reflection.GeneratedProtocolMessageType('LocationEPMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONEPMESSAGE,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationEPMessage)
  })
_sym_db.RegisterMessage(LocationEPMessage)

_LOCATIONEPSERVICE = DESCRIPTOR.services_by_name['LocationEPService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONEPMESSAGE._serialized_start=18
  _LOCATIONEPMESSAGE._serialized_end=116
  _LOCATIONEPSERVICE._serialized_start=118
  _LOCATIONEPSERVICE._serialized_end=187
# @@protoc_insertion_point(module_scope)
