apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-location-service
  name: location-service
spec:
  ports:
  - name: "5071"
    port: 5071
    nodePort: 30006
  selector:
    service: uda-location-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-location-service
  name: uda-location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-location-service
  template:
    metadata:
      labels:
        service: uda-location-service
    spec:
      containers:
      - image: ap84gray/uda-location-service:latest
        name: uda-location-service
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: apachekafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: apachekafka-env
              key: KAFKA_SERVER
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always



